"""make email unique

Revision ID: 26c7c044510a
Revises: 28f60d1d0a71
Create Date: 2016-09-02 19:26:40.021079

"""

# revision identifiers, used by Alembic.
revision = '26c7c044510a'
down_revision = '28f60d1d0a71'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'users', ['email'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    ### end Alembic commands ###
