"""make read field non-nullable

Revision ID: 5f9738ffb23d
Revises: dedb1c46cf1a
Create Date: 2016-09-21 16:05:07.240418

"""

# revision identifiers, used by Alembic.
revision = '5f9738ffb23d'
down_revision = 'dedb1c46cf1a'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('replies', 'read',
               existing_type=mysql.TINYINT(display_width=1),
               type_=sa.Boolean(),
               nullable=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('replies', 'read',
               existing_type=sa.Boolean(),
               type_=mysql.TINYINT(display_width=1),
               nullable=True)
    ### end Alembic commands ###
