"""add backref in enquiries to users

Revision ID: 5eb4e14a4e9c
Revises: 26c7c044510a
Create Date: 2016-09-02 21:57:50.270092

"""

# revision identifiers, used by Alembic.
revision = '5eb4e14a4e9c'
down_revision = '26c7c044510a'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
