"""add messaging related tables

Revision ID: 60e230cb9b17
Revises: 5eb4e14a4e9c
Create Date: 2016-09-15 15:23:31.809462

"""

# revision identifiers, used by Alembic.
revision = '60e230cb9b17'
down_revision = '5eb4e14a4e9c'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('replies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('message', sa.String(), nullable=False),
    sa.Column('enquiry_id', sa.Integer(), nullable=True),
    sa.Column('from_user', sa.Integer(), nullable=True),
    sa.Column('to_user', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['enquiry_id'], ['enquiry_data.id'], ),
    sa.ForeignKeyConstraint(['from_user'], ['user.user_id'], ),
    sa.ForeignKeyConstraint(['to_user'], ['user.user_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('enquiry_data', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'enquiry_data', 'user', ['user_id'], ['user_id'])
    op.create_index(op.f('ix_leads_consume_id'), 'leads_consume', ['id'], unique=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'enquiry_data', type_='foreignkey')
    op.drop_column('enquiry_data', 'user_id')
    op.drop_table('replies')
    ### end Alembic commands ###
