"""migrate the demo db

Revision ID: a7b926f9cef5
Revises: 5f9738ffb23d
Create Date: 2016-10-07 12:45:12.643869

"""

# revision identifiers, used by Alembic.
revision = 'a7b926f9cef5'
down_revision = '5f9738ffb23d'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('replies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('enquiry_id', sa.Integer(), nullable=True),
    sa.Column('from_user', sa.Integer(), nullable=True),
    sa.Column('to_user', sa.Integer(), nullable=True),
    sa.Column('local_msg_id', sa.Integer(), nullable=True),
    sa.Column('read', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['enquiry_id'], ['enquiry_data.id'], ),
    sa.ForeignKeyConstraint(['from_user'], ['user.user_id'], ),
    sa.ForeignKeyConstraint(['to_user'], ['user.user_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_foreign_key(None, 'enquiry_data', 'user', ['user_id'], ['user_id'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'enquiry_data', type_='foreignkey')
    op.drop_table('replies')
    ### end Alembic commands ###
