"""add type column for messages

Revision ID: db0a696c3d95
Revises: ebc6a6924556
Create Date: 2016-10-13 17:35:51.524313

"""

# revision identifiers, used by Alembic.
revision = 'db0a696c3d95'
down_revision = 'ebc6a6924556'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('replies', sa.Column('type', sa.Text(), nullable=False))
    op.alter_column('replies', 'read',
               existing_type=mysql.TINYINT(display_width=1),
               type_=sa.Boolean(),
               existing_nullable=False)
    op.alter_column('replies', 'received',
               existing_type=mysql.TINYINT(display_width=1),
               type_=sa.Boolean(),
               existing_nullable=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('replies', 'received',
               existing_type=sa.Boolean(),
               type_=mysql.TINYINT(display_width=1),
               existing_nullable=False)
    op.alter_column('replies', 'read',
               existing_type=sa.Boolean(),
               type_=mysql.TINYINT(display_width=1),
               existing_nullable=False)
    op.drop_column('replies', 'type')
    ### end Alembic commands ###
