"""add read and local_msg_id

Revision ID: dedb1c46cf1a
Revises: fdcf9ebf8c89
Create Date: 2016-09-20 20:08:44.623224

"""

# revision identifiers, used by Alembic.
revision = 'dedb1c46cf1a'
down_revision = 'fdcf9ebf8c89'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('replies', sa.Column('local_msg_id', sa.Integer(), nullable=True))
    op.add_column('replies', sa.Column('read', sa.Boolean(), nullable=True))
    op.alter_column('replies', 'message',
               existing_type=mysql.TEXT(),
               nullable=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('replies', 'message',
               existing_type=mysql.TEXT(),
               nullable=True)
    op.drop_column('replies', 'read')
    op.drop_column('replies', 'local_msg_id')
    ### end Alembic commands ###
